quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/spotifake
quarkus.hibernate-orm.database.generation=none
quarkus.log.level=INFO
quarkus.hibernate-orm.log.sql=false
quarkus.http.port=8080
